# Generated by Django 3.0.2 on 2020-04-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Reteta',
        ),
        migrations.RenameField(
            model_name='reteta',
            old_name='description',
            new_name='descriere',
        ),
        migrations.RenameField(
            model_name='reteta',
            old_name='title',
            new_name='nume',
        ),
    ]
