# Generated by Django 3.0.2 on 2020-04-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipe', '0002_auto_20200422_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reteta',
            new_name='Recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='descriere',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='nume',
            new_name='name',
        ),
    ]
