# Generated by Django 3.0.2 on 2020-04-22 14:47

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipe', '0003_auto_20200422_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug'),
        ),
    ]
